
<p>Меню сайта:</p>

<li<?=$cur1?>><a href="user-id.php"> - Список пользователей  [users]</a></li>

<li<?=$cur2?>><a href="user-green-id.php"> - Список неаторизованных пользователей  [users_green]</a></li>

<li<?=$cur2?>><a href="message_db.php"> - Список сообщений пользователей  [mess]</a></li>

<li<?=$cur2?>><a href="message_id.php"> - Список id сообщений пользователей  [message_id]</a></li>

<li<?=$cur2?>><a href="user_menu_id.php"> - Список id меню пользователей  [menu_user_id]</a></li>

<li<?=$cur2?>><a href="user_menu.php"> - Список меню  [menu_user]</a></li>
